# Build runtime image
FROM microsoft/aspnetcore:2.0
WORKDIR /app
COPY pub/ ./
# Copy configs and certs
ADD Configs_DevTest_tmp /X/Configs
ADD TheBallCerts /X/TheBallCerts
RUN ls -l /X/Configs
ENTRYPOINT ["dotnet", "WebCoreLayer.dll"]