# Build runtime image
FROM microsoft/aspnetcore:2.0
WORKDIR /app
#COPY pub/ ./
ADD https://tbdevops.file.core.windows.net/deploy/20171221.2116_dev_319586774f18c90a0da977026a670bbe3dc15b01/WebApp.tar.gz?sv=2015-12-11&ss=f&srt=sco&sp=rl&se=2019-01-17T01:19:07Z&st=2017-01-16T17:19:07Z&spr=https&sig=vyaYn6ft2jTrGGC9hQ09FCGKDyzI35BUWVJjiOAsQTs%3D ./
# Copy configs and certs
RUN tar xvfz ./WebApp.tar.gz
RUN ls -l ./
ENTRYPOINT ["dotnet", "WebCoreLayer.dll"]